#ifndef __INVISIONNATIVE_FMOD_H__
#define __INVISIONNATIVE_FMOD_H__

#include <InvisionHandle.h>
#include "invisionnative.h"

extern "C"
{
	/*
	 * Enumeration DSP_ITECHO
	 */
	#define DSP_ITECHO _int
	#define DSP_ITECHO_WETDRY_MIX 0x0
	#define DSP_ITECHO_FEEDBACK 0x1
	#define DSP_ITECHO_LEFT_DELAY 0x2
	#define DSP_ITECHO_RIGHT_DELAY 0x3
	#define DSP_ITECHO_PAN_DELAY 0x4
	
	/*
	 * Enumeration DSP_CHORUS
	 */
	#define DSP_CHORUS _int
	#define DSP_CHORUS_DRYMIX 0x0
	#define DSP_CHORUS_WETMIX1 0x1
	#define DSP_CHORUS_WETMIX2 0x2
	#define DSP_CHORUS_WETMIX3 0x3
	#define DSP_CHORUS_DELAY 0x4
	#define DSP_CHORUS_RATE 0x5
	#define DSP_CHORUS_DEPTH 0x6
	#define DSP_CHORUS_FEEDBACK 0x7
	
	/*
	 * Enumeration CHANNEL_INDEX
	 */
	#define CHANNEL_INDEX _int
	#define CHANNEL_INDEX_CHANNEL_FREE 0x0
	#define CHANNEL_INDEX_CHANNEL_REUSE 0x1
	
	/*
	 * Enumeration SOUND_FORMAT
	 */
	#define SOUND_FORMAT _int
	#define SOUND_FORMAT_NONE 0x0
	#define SOUND_FORMAT_PCM8 0x1
	#define SOUND_FORMAT_PCM16 0x2
	#define SOUND_FORMAT_PCM24 0x3
	#define SOUND_FORMAT_PCM32 0x4
	#define SOUND_FORMAT_PCMFLOAT 0x5
	#define SOUND_FORMAT_GCADPCM 0x6
	#define SOUND_FORMAT_IMAADPCM 0x7
	#define SOUND_FORMAT_VAG 0x8
	#define SOUND_FORMAT_XMA 0x9
	#define SOUND_FORMAT_MPEG 0xA
	#define SOUND_FORMAT_CELT 0xB
	#define SOUND_FORMAT_MAX 0xC
	
	/*
	 * Enumeration DSP_TREMOLO
	 */
	#define DSP_TREMOLO _int
	#define DSP_TREMOLO_FREQUENCY 0x0
	#define DSP_TREMOLO_DEPTH 0x1
	#define DSP_TREMOLO_SHAPE 0x2
	#define DSP_TREMOLO_SKEW 0x3
	#define DSP_TREMOLO_DUTY 0x4
	#define DSP_TREMOLO_SQUARE 0x5
	#define DSP_TREMOLO_PHASE 0x6
	#define DSP_TREMOLO_SPREAD 0x7
	
	/*
	 * Enumeration DSP_DELAY
	 */
	#define DSP_DELAY _int
	#define DSP_DELAY_CH0 0x0
	#define DSP_DELAY_CH1 0x1
	#define DSP_DELAY_CH2 0x2
	#define DSP_DELAY_CH3 0x3
	#define DSP_DELAY_CH4 0x4
	#define DSP_DELAY_CH5 0x5
	#define DSP_DELAY_CH6 0x6
	#define DSP_DELAY_CH7 0x7
	#define DSP_DELAY_CH8 0x8
	#define DSP_DELAY_CH9 0x9
	#define DSP_DELAY_CH10 0xA
	#define DSP_DELAY_CH11 0xB
	#define DSP_DELAY_CH12 0xC
	#define DSP_DELAY_CH13 0xD
	#define DSP_DELAY_CH14 0xE
	#define DSP_DELAY_CH15 0xF
	#define DSP_DELAY_MAX_DELAY 0x10
	
	/*
	 * Enumeration TAG_DATA_TYPE
	 */
	#define TAG_DATA_TYPE _int
	#define TAG_DATA_TYPE_BINARY 0x0
	#define TAG_DATA_TYPE_INT 0x1
	#define TAG_DATA_TYPE_FLOAT 0x2
	#define TAG_DATA_TYPE_STRING 0x3
	#define TAG_DATA_TYPE_STRING_UTF16 0x4
	#define TAG_DATA_TYPE_STRING_UTF16_BE 0x5
	#define TAG_DATA_TYPE_STRING_UTF8 0x6
	#define TAG_DATA_TYPE_CDTOC 0x7
	#define TAG_DATA_TYPE_MAX 0x8
	
	/*
	 * Enumeration SYSTEM_CALLBACK_TYPE
	 */
	#define SYSTEM_CALLBACK_TYPE _int
	#define SYSTEM_CALLBACK_TYPE_DEVICE_LIST_CHANGED 0x0
	#define SYSTEM_CALLBACK_TYPE_DEVICE_LOST 0x1
	#define SYSTEM_CALLBACK_TYPE_MEMORY_ALLOCATION_FAILED 0x2
	#define SYSTEM_CALLBACK_TYPE_THREAD_CREATED 0x3
	#define SYSTEM_CALLBACK_TYPE_BADDSP_CONNECTION 0x4
	#define SYSTEM_CALLBACK_TYPE_BADDSP_LEVEL 0x5
	#define SYSTEM_CALLBACK_TYPE_MAX 0x6
	
	/*
	 * Enumeration OUTPUT_TYPE
	 */
	#define OUTPUT_TYPE _int
	#define OUTPUT_TYPE_AUTO_DETECT 0x0
	#define OUTPUT_TYPE_UNKNOWN 0x1
	#define OUTPUT_TYPE_NO_SOUND 0x2
	#define OUTPUT_TYPE_WAV_WRITER 0x3
	#define OUTPUT_TYPE_NO_SOUND_NRT 0x4
	#define OUTPUT_TYPE_WAV_WRITER_NRT 0x5
	#define OUTPUT_TYPE_DSOUND 0x6
	#define OUTPUT_TYPE_WINMM 0x7
	#define OUTPUT_TYPE_WASAPI 0x8
	#define OUTPUT_TYPE_ASIO 0x9
	#define OUTPUT_TYPE_OSS 0xA
	#define OUTPUT_TYPE_ALSA 0xB
	#define OUTPUT_TYPE_ESD 0xC
	#define OUTPUT_TYPE_PULSE_AUDIO 0xD
	#define OUTPUT_TYPE_CORE_AUDIO 0xE
	#define OUTPUT_TYPE_PS2 0xF
	#define OUTPUT_TYPE_PS3 0x10
	#define OUTPUT_TYPE_XBOX360 0x11
	#define OUTPUT_TYPE_PSP 0x12
	#define OUTPUT_TYPE_WII 0x13
	#define OUTPUT_TYPE_ANDROID 0x14
	#define OUTPUT_TYPE_THREE_DS 0x15
	#define OUTPUT_TYPE_MAX 0x16
	
	/*
	 * Enumeration DSP_TYPE
	 */
	#define DSP_TYPE _int
	#define DSP_TYPE_UNKNOWN 0x0
	#define DSP_TYPE_MIXER 0x1
	#define DSP_TYPE_OSCILLATOR 0x2
	#define DSP_TYPE_LOWPASS 0x3
	#define DSP_TYPE_IT_LOWPASS 0x4
	#define DSP_TYPE_HIGHPASS 0x5
	#define DSP_TYPE_ECHO 0x6
	#define DSP_TYPE_FLANGE 0x7
	#define DSP_TYPE_DISTORTION 0x8
	#define DSP_TYPE_NORMALIZE 0x9
	#define DSP_TYPE_PARAMEQ 0xA
	#define DSP_TYPE_PITCH_SHIFT 0xB
	#define DSP_TYPE_CHORUS 0xC
	#define DSP_TYPE_REVERB 0xD
	#define DSP_TYPE_VST_PLUGIN 0xE
	#define DSP_TYPE_WINAMP_PLUGIN 0xF
	#define DSP_TYPE_ITECHO 0x10
	#define DSP_TYPE_COMPRESSOR 0x11
	#define DSP_TYPE_SFX_REVERB 0x12
	#define DSP_TYPE_LOWPASS_SIMPLE 0x13
	#define DSP_TYPE_DELAY 0x14
	#define DSP_TYPE_TREMOLO 0x15
	#define DSP_TYPE_LADSPA_PLUGIN 0x16
	
	/*
	 * Enumeration DSP_PARAMEQ
	 */
	#define DSP_PARAMEQ _int
	#define DSP_PARAMEQ_CENTER 0x0
	#define DSP_PARAMEQ_BANDWIDTH 0x1
	#define DSP_PARAMEQ_GAIN 0x2
	
	/*
	 * Enumeration SPEAKER_MODE
	 */
	#define SPEAKER_MODE _int
	#define SPEAKER_MODE_RAW 0x0
	#define SPEAKER_MODE_MONO 0x1
	#define SPEAKER_MODE_STEREO 0x2
	#define SPEAKER_MODE_QUAD 0x3
	#define SPEAKER_MODE_SURROUND 0x4
	#define SPEAKER_MODE_FIVE_POINT1 0x5
	#define SPEAKER_MODE_SEVEN_POINT1 0x6
	#define SPEAKER_MODE_PROLOGIC 0x7
	#define SPEAKER_MODE_MAX 0x8
	
	/*
	 * Enumeration DSP_FFT_WINDOW
	 */
	#define DSP_FFT_WINDOW _int
	#define DSP_FFT_WINDOW_RECT 0x0
	#define DSP_FFT_WINDOW_TRIANGLE 0x1
	#define DSP_FFT_WINDOW_HAMMING 0x2
	#define DSP_FFT_WINDOW_HANNING 0x3
	#define DSP_FFT_WINDOW_BLACKMAN 0x4
	#define DSP_FFT_WINDOW_BLACK_MANHARRIS 0x5
	#define DSP_FFT_WINDOW_MAX 0x6
	
	/*
	 * Enumeration DELAY_TYPE
	 */
	#define DELAY_TYPE _int
	#define DELAY_TYPE_END_MS 0x0
	#define DELAY_TYPE_DSPCLOCK_START 0x1
	#define DELAY_TYPE_DSPCLOCK_END 0x2
	#define DELAY_TYPE_DSPCLOCK_PAUSE 0x3
	#define DELAY_TYPE_MAX 0x4
	
	/*
	 * Enumeration THREAD
	 */
	#define THREAD _int
	#define THREAD_DEFAULT 0x0
	#define THREAD_CORE0_THREAD0 0x1
	#define THREAD_CORE0_THREAD1 0x2
	#define THREAD_CORE1_THREAD0 0x3
	#define THREAD_CORE1_THREAD1 0x4
	#define THREAD_CORE2_THREAD0 0x5
	#define THREAD_CORE2_THREAD1 0x6
	#define THREAD_MAX 0x7
	
	/*
	 * Enumeration TAG_TYPE
	 */
	#define TAG_TYPE _int
	#define TAG_TYPE_UNKNOWN 0x0
	#define TAG_TYPE_ID3_V1 0x1
	#define TAG_TYPE_ID3_V2 0x2
	#define TAG_TYPE_VORBIS_COMMENT 0x3
	#define TAG_TYPE_SHOUTCAST 0x4
	#define TAG_TYPE_ICECAST 0x5
	#define TAG_TYPE_ASF 0x6
	#define TAG_TYPE_MIDI 0x7
	#define TAG_TYPE_PLAYLIST 0x8
	#define TAG_TYPE_FMOD 0x9
	#define TAG_TYPE_USER 0xA
	#define TAG_TYPE_MAX 0xB
	
	/*
	 * Enumeration SOUND_GROUP_BEHAVIOR
	 */
	#define SOUND_GROUP_BEHAVIOR _int
	#define SOUND_GROUP_BEHAVIOR_FAIL 0x0
	#define SOUND_GROUP_BEHAVIOR_MUTE 0x1
	#define SOUND_GROUP_BEHAVIOR_STEALLOWEST 0x2
	#define SOUND_GROUP_BEHAVIOR_MAX 0x3
	
	/*
	 * Enumeration PLUGIN_TYPE
	 */
	#define PLUGIN_TYPE _int
	#define PLUGIN_TYPE_OUTPUT 0x0
	#define PLUGIN_TYPE_CODEC 0x1
	#define PLUGIN_TYPE_DSP 0x2
	#define PLUGIN_TYPE_MAX 0x3
	
	/*
	 * Enumeration DSP_SFX_REVERB
	 */
	#define DSP_SFX_REVERB _int
	#define DSP_SFX_REVERB_DRY_LEVEL 0x0
	#define DSP_SFX_REVERB_ROOM 0x1
	#define DSP_SFX_REVERB_ROOM_HF 0x2
	#define DSP_SFX_REVERB_ROOM_ROLLOFF_FACTOR 0x3
	#define DSP_SFX_REVERB_DECAY_TIME 0x4
	#define DSP_SFX_REVERB_DECAY_HFRATIO 0x5
	#define DSP_SFX_REVERB_REFLECTIONS_LEVEL 0x6
	#define DSP_SFX_REVERB_REFLECTIONS_DELAY 0x7
	#define DSP_SFX_REVERB_REVERB_LEVEL 0x8
	#define DSP_SFX_REVERB_REVERB_DELAY 0x9
	#define DSP_SFX_REVERB_DIFFUSION 0xA
	#define DSP_SFX_REVERB_DENSITY 0xB
	#define DSP_SFX_REVERB_HF_REFERENCE 0xC
	#define DSP_SFX_REVERB_ROOM_LF 0xD
	#define DSP_SFX_REVERB_LF_REFERENCE 0xE
	
	/*
	 * Enumeration CHANNEL_CALLBACK_TYPE
	 */
	#define CHANNEL_CALLBACK_TYPE _int
	#define CHANNEL_CALLBACK_TYPE_END 0x0
	#define CHANNEL_CALLBACK_TYPE_VIRTUALVOICE 0x1
	#define CHANNEL_CALLBACK_TYPE_SYNCPOINT 0x2
	#define CHANNEL_CALLBACK_TYPE_OCCLUSION 0x3
	#define CHANNEL_CALLBACK_TYPE_MAX 0x4
	
	/*
	 * Enumeration RESULT
	 */
	#define RESULT _int
	#define RESULT_FMOD_OK 0x0
	#define RESULT_ALREADY_LOCKED 0x1
	#define RESULT_BAD_COMMAND 0x2
	#define RESULT_CDDA_DRIVERS 0x3
	#define RESULT_CDDA_INIT 0x4
	#define RESULT_CDDA_INVALID_DEVICE 0x5
	#define RESULT_CDDA_NO_AUDIO 0x6
	#define RESULT_CDDA_NO_DEVICES 0x7
	#define RESULT_CDDA_NO_DISC 0x8
	#define RESULT_CDDA_READ 0x9
	#define RESULT_CHANNEL_ALLOC 0xA
	#define RESULT_CHANNEL_STOLEN 0xB
	#define RESULT_COM 0xC
	#define RESULT_DMA 0xD
	#define RESULT_DSP_CONNECTION 0xE
	#define RESULT_DSP_FORMAT 0xF
	#define RESULT_DSP_NOT_FOUND 0x10
	#define RESULT_DSP_RUNNING 0x11
	#define RESULT_DSP_TOOMANY_CONNECTIONS 0x12
	#define RESULT_FILE_BAD 0x13
	#define RESULT_FILE_COULD_NOT_SEEK 0x14
	#define RESULT_FILE_DISK_EJECTED 0x15
	#define RESULT_FILE_EOF 0x16
	#define RESULT_FILE_NOT_FOUND 0x17
	#define RESULT_FILE_UNWANTED 0x18
	#define RESULT_FORMAT 0x19
	#define RESULT_HTTP 0x1A
	#define RESULT_HTTP_ACCESS 0x1B
	#define RESULT_HTTP_PROXY_AUTH 0x1C
	#define RESULT_HTTP_SERVER_ERROR 0x1D
	#define RESULT_HTTP_TIMEOUT 0x1E
	#define RESULT_INITIALIZATION 0x1F
	#define RESULT_INITIALIZED 0x20
	#define RESULT_INTERNAL 0x21
	#define RESULT_INVALID_ADDRESS 0x22
	#define RESULT_INVALID_FLOAT 0x23
	#define RESULT_INVALID_HANDLE 0x24
	#define RESULT_INVALID_PARAM 0x25
	#define RESULT_INVALID_POSITION 0x26
	#define RESULT_INVALID_SPEAKER 0x27
	#define RESULT_INVALID_SYNCPOINT 0x28
	#define RESULT_INVALID_VECTOR 0x29
	#define RESULT_IRX 0x2A
	#define RESULT_MAXAUDIBLE 0x2B
	#define RESULT_MEMORY 0x2C
	#define RESULT_MEMORY_CANTPOINT 0x2D
	#define RESULT_MEMORY_IOP 0x2E
	#define RESULT_MEMORY_SRAM 0x2F
	#define RESULT_NEEDS2_D 0x30
	#define RESULT_NEEDS3_D 0x31
	#define RESULT_NEEDS_HARDWARE 0x32
	#define RESULT_NEEDS_SOFTWARE 0x33
	#define RESULT_NET_CONNECT 0x34
	#define RESULT_NET_SOCKET_ERROR 0x35
	#define RESULT_NET_URL 0x36
	#define RESULT_NET_WOULD_BLOCK 0x37
	#define RESULT_NOT_READY 0x38
	#define RESULT_OUTPUT_ALLOCATED 0x39
	#define RESULT_OUTPUT_CREATEBUFFER 0x3A
	#define RESULT_OUTPUT_DRIVERCALL 0x3B
	#define RESULT_OUTPUT_ENUMERATION 0x3C
	#define RESULT_OUTPUT_FORMAT 0x3D
	#define RESULT_OUTPUT_INIT 0x3E
	#define RESULT_OUTPUT_NO_HARDWARE 0x3F
	#define RESULT_OUTPUT_NO_SOFTWARE 0x40
	#define RESULT_PAN 0x41
	#define RESULT_PLUGIN 0x42
	#define RESULT_PLUGIN_INSTANCES 0x43
	#define RESULT_PLUGIN_MISSING 0x44
	#define RESULT_PLUGIN_RESOURCE 0x45
	#define RESULT_PRELOADED 0x46
	#define RESULT_PROGRAMMER_SOUND 0x47
	#define RESULT_RECORD 0x48
	#define RESULT_REVERB_INSTANCE 0x49
	#define RESULT_SUBSOUND_ALLOCATED 0x4A
	#define RESULT_SUBSOUND_CANTMOVE 0x4B
	#define RESULT_SUBSOUND_MODE 0x4C
	#define RESULT_SUBSOUNDS 0x4D
	#define RESULT_TAG_NOT_FOUND 0x4E
	#define RESULT_TOO_MANY_CHANNELS 0x4F
	#define RESULT_UNIMPLEMENTED 0x50
	#define RESULT_UNINITIALIZED 0x51
	#define RESULT_UNSUPPORTED 0x52
	#define RESULT_UPDATE 0x53
	#define RESULT_VERSION 0x54
	#define RESULT_EVENT_FAILED 0x55
	#define RESULT_EVENT_INFOONLY 0x56
	#define RESULT_EVENT_INTERNAL 0x57
	#define RESULT_EVENT_MAX_STREAMS 0x58
	#define RESULT_EVENT_MISMATCH 0x59
	#define RESULT_EVENT_NAME_CONFLICT 0x5A
	#define RESULT_EVENT_NOT_FOUND 0x5B
	#define RESULT_EVENT_NEEDS_SIMPLE 0x5C
	#define RESULT_EVENT_GUID_CONFLICT 0x5D
	#define RESULT_EVENT_ALREADY_LOADED 0x5E
	#define RESULT_MUSIC_UNINITIALIZED 0x5F
	#define RESULT_MUSIC_NOT_FOUND 0x60
	#define RESULT_MUSIC_NOCALLBACK 0x61
	
	/*
	 * Enumeration DSP_NORMALIZE
	 */
	#define DSP_NORMALIZE _int
	#define DSP_NORMALIZE_FADE_TIME 0x0
	#define DSP_NORMALIZE_THRESH_HOLD 0x1
	#define DSP_NORMALIZE_MAX_AMP 0x2
	
	/*
	 * Enumeration DSP_IT_LOW_PASS
	 */
	#define DSP_IT_LOW_PASS _int
	#define DSP_IT_LOW_PASS_CUTOFF 0x0
	#define DSP_IT_LOW_PASS_RESONANCE 0x1
	
	/*
	 * Enumeration DSP_FLANGE
	 */
	#define DSP_FLANGE _int
	#define DSP_FLANGE_DRY_MIX 0x0
	#define DSP_FLANGE_WET_MIX 0x1
	#define DSP_FLANGE_DEPTH 0x2
	#define DSP_FLANGE_RATE 0x3
	
	/*
	 * Enumeration SPEAKER_MAP_TYPE
	 */
	#define SPEAKER_MAP_TYPE _int
	#define SPEAKER_MAP_TYPE_DEFAULT 0x0
	#define SPEAKER_MAP_TYPE_ALL_MONO 0x1
	#define SPEAKER_MAP_TYPE_ALL_STEREO 0x2
	#define SPEAKER_MAP_TYPE_FIFTY_ONE_PROTOOLS 0x3
	
	/*
	 * Enumeration OPEN_STATE
	 */
	#define OPEN_STATE _int
	#define OPEN_STATE_READY 0x0
	#define OPEN_STATE_LOADING 0x1
	#define OPEN_STATE_ERROR 0x2
	#define OPEN_STATE_CONNECTING 0x3
	#define OPEN_STATE_BUFFERING 0x4
	#define OPEN_STATE_SEEKING 0x5
	#define OPEN_STATE_PLAYING 0x6
	#define OPEN_STATE_SET_POSITION 0x7
	#define OPEN_STATE_MAX 0x8
	
	/*
	 * Enumeration DSP_LOW_PASS_SIMPLE
	 */
	#define DSP_LOW_PASS_SIMPLE _int
	#define DSP_LOW_PASS_SIMPLE_CUT_OFF 0x0
	
	/*
	 * Enumeration DSP_DISTORTION
	 */
	#define DSP_DISTORTION _int
	#define DSP_DISTORTION_LEVEL 0x0
	
	/*
	 * Enumeration DSP_COMPRESSOR
	 */
	#define DSP_COMPRESSOR _int
	#define DSP_COMPRESSOR_THRESHOLD 0x0
	#define DSP_COMPRESSOR_ATTACK 0x1
	#define DSP_COMPRESSOR_RELEASE 0x2
	#define DSP_COMPRESSOR_GAIN_MAKE_UP 0x3
	
	/*
	 * Enumeration SOUND_TYPE
	 */
	#define SOUND_TYPE _int
	#define SOUND_TYPE_UNKNOWN 0x0
	#define SOUND_TYPE_AAC 0x1
	#define SOUND_TYPE_AIFF 0x2
	#define SOUND_TYPE_ASF 0x3
	#define SOUND_TYPE_AT3 0x4
	#define SOUND_TYPE_CDDA 0x5
	#define SOUND_TYPE_DLS 0x6
	#define SOUND_TYPE_FLAC 0x7
	#define SOUND_TYPE_FSB 0x8
	#define SOUND_TYPE_GCADPCM 0x9
	#define SOUND_TYPE_IT 0xA
	#define SOUND_TYPE_MIDI 0xB
	#define SOUND_TYPE_MOD 0xC
	#define SOUND_TYPE_MPEG 0xD
	#define SOUND_TYPE_OGGVORBIS 0xE
	#define SOUND_TYPE_PLAYLIST 0xF
	#define SOUND_TYPE_RAW 0x10
	#define SOUND_TYPE_S3_M 0x11
	#define SOUND_TYPE_SF2 0x12
	#define SOUND_TYPE_USER 0x13
	#define SOUND_TYPE_WAV 0x14
	#define SOUND_TYPE_XM 0x15
	#define SOUND_TYPE_XMA 0x16
	#define SOUND_TYPE_VAG 0x17
	#define SOUND_TYPE_AUDIO_QUEUE 0x18
	#define SOUND_TYPE_XWMA 0x19
	#define SOUND_TYPE_BCWAV 0x1A
	#define SOUND_TYPE_MAX 0x1B
	
	/*
	 * Enumeration PSP_OUTPUT_MODE
	 */
	#define PSP_OUTPUT_MODE _int
	#define PSP_OUTPUT_MODE_SIMPLE_AUDIO 0x0
	#define PSP_OUTPUT_MODE_LIB_WAVE 0x1
	
	/*
	 * Enumeration DSP_PITCH_SHIFT
	 */
	#define DSP_PITCH_SHIFT _int
	#define DSP_PITCH_SHIFT_PITCH 0x0
	#define DSP_PITCH_SHIFT_FFT_SIZE 0x1
	#define DSP_PITCH_SHIFT_OVERLAP 0x2
	#define DSP_PITCH_SHIFT_MAX_CHANNELS 0x3
	
	/*
	 * Enumeration DSP_ECHO
	 */
	#define DSP_ECHO _int
	#define DSP_ECHO_DELAY 0x0
	#define DSP_ECHO_DECAY_RATIO 0x1
	#define DSP_ECHO_MAX_CHANNELS 0x2
	#define DSP_ECHO_DRY_MIX 0x3
	#define DSP_ECHO_WET_MIX 0x4
	
	/*
	 * Enumeration DSP_REVERB
	 */
	#define DSP_REVERB _int
	#define DSP_REVERB_ROOM_SIZE 0x0
	#define DSP_REVERB_DAMP 0x1
	#define DSP_REVERB_WET_MIX 0x2
	#define DSP_REVERB_DRY_MIX 0x3
	#define DSP_REVERB_WIDTH 0x4
	#define DSP_REVERB_MODE 0x5
	
	/*
	 * Enumeration DSP_HIGH_PASS
	 */
	#define DSP_HIGH_PASS _int
	#define DSP_HIGH_PASS_CUTOFF 0x0
	#define DSP_HIGH_PASS_RESONANCE 0x1
	
	/*
	 * Enumeration SPEAKER
	 */
	#define SPEAKER _int
	#define SPEAKER_FRONT_LEFT 0x0
	#define SPEAKER_FRONT_RIGHT 0x1
	#define SPEAKER_FRONT_CENTER 0x2
	#define SPEAKER_LOW_FREQUENCY 0x3
	#define SPEAKER_BACK_LEFT 0x4
	#define SPEAKER_BACK_RIGHT 0x5
	#define SPEAKER_SIDE_LEFT 0x6
	#define SPEAKER_SIDE_RIGHT 0x7
	#define SPEAKER_MAX 0x8
	#define SPEAKER_MONO 0x9
	#define SPEAKER_NULL 0xA
	#define SPEAKER_SBL 0xB
	#define SPEAKER_SBR 0xC
	
	/*
	 * Enumeration DSP_RESAMPLER
	 */
	#define DSP_RESAMPLER _int
	#define DSP_RESAMPLER_NOINTERP 0x0
	#define DSP_RESAMPLER_LINEAR 0x1
	#define DSP_RESAMPLER_CUBIC 0x2
	#define DSP_RESAMPLER_SPLINE 0x3
	#define DSP_RESAMPLER_MAX 0x4
	
	/*
	 * Enumeration DSP_OSCILLATOR
	 */
	#define DSP_OSCILLATOR _int
	#define DSP_OSCILLATOR_TYPE 0x0
	#define DSP_OSCILLATOR_RATE 0x1
	
	
	/*
	 * Prototypes
	 */
	
	
	
	
	
}


#ifdef __cplusplus

using namespace invision;

/*
 * Initializer
 */
struct InVisionNative_FMod
{
	InVisionNative_FMod()
	{
	}
};

static InVisionNative_FMod __initInVisionNative_FMod;

#endif // __cplusplus
#endif // __INVISIONNATIVE_FMOD_H__
