import Karel.Controller

karel = Karel()
karel.TurnOn()
karel.TurnLeft()
karel.Move()
karel.Move()
karel.TurnLeft()
karel.TurnLeft()
karel.TurnLeft()
karel.Move()
karel.Move()
karel.Move()
karel.TurnLeft()
karel.TurnLeft()
karel.TurnLeft()
karel.Move()
karel.Move()
karel.PickBeeper()
karel.TurnLeft()
karel.TurnLeft()
karel.Move()
karel.Move()
karel.Move()
karel.PutBeeper()
karel.TurnOff()
