namespace InVision.Bullet.Dynamics.ConstraintSolver
{
	public enum SliderFlags
	{
		BT_SLIDER_FLAGS_CFM_DIRLIN = (1 << 0),
		BT_SLIDER_FLAGS_ERP_DIRLIN = (1 << 1),
		BT_SLIDER_FLAGS_CFM_DIRANG = (1 << 2),
		BT_SLIDER_FLAGS_ERP_DIRANG = (1 << 3),
		BT_SLIDER_FLAGS_CFM_ORTLIN = (1 << 4),
		BT_SLIDER_FLAGS_ERP_ORTLIN = (1 << 5),
		BT_SLIDER_FLAGS_CFM_ORTANG = (1 << 6),
		BT_SLIDER_FLAGS_ERP_ORTANG = (1 << 7),
		BT_SLIDER_FLAGS_CFM_LIMLIN = (1 << 8),
		BT_SLIDER_FLAGS_ERP_LIMLIN = (1 << 9),
		BT_SLIDER_FLAGS_CFM_LIMANG = (1 << 10),
		BT_SLIDER_FLAGS_ERP_LIMANG = (1 << 11)
	};
}